controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
blog_list:
    path: /register
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\UserController::createUser
    methods:    POST